// txt imports
import SAMPLE_TEXT from './lorem.txt';
// css imports
import './reset.css';
import './index.css';
import './dropdown.css';

// js imports
import Utility from './utility';
import MenuBar from './dropdown';
import NAV_ELEMENTS from './navElements';
import Slider from './slider';
import { IMAGE_FILEPATH, sliderPics } from './sliderPics';

// data imports


const loadGenericBody = () => {
  const div = document.createElement("div");
  const h1 = document.createElement("h1");
  const description = document.createElement("p");

  h1.textContent = "Lorem Ipsum";
  description.textContent = SAMPLE_TEXT; 
  
  div.classList.add("sample-text");

  div.append(h1, description);

  return div;
}

(function main() {

  const menubar = new MenuBar("dropdown-menu");
  MenuBar.addElementsToHeader(menubar, NAV_ELEMENTS);
  document.body.append(menubar.getMenu(), loadGenericBody());

  const images = Utility.importAllImages();
  sliderPics.forEach((pic) => {
    // replace the path of the sliderPics with the destination path generated by webpack.
    pic.path = images[pic.path];
  });

  console.log(JSON.stringify(sliderPics));

  const nationalParkSlider = new Slider(sliderPics, 3);
  
  document.body.append(nationalParkSlider.slider);

  Slider.playSlideshowOnWindowLoad(nationalParkSlider);

}());
